[versions]
agp = "8.9.1"
cardview = "1.0.0"
commonsIo = "2.21.0"
compiler = "5.0.5"
coreSplashscreen = "1.2.0"
coreSplashscreenVersion = "1.1.0"
gson = "2.13.2"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.2"
constraintlayout = "2.2.1"
navigationFragment = "2.9.6"
navigationUi = "2.7.6"
poiOoxml = "5.5.1"
recyclerview = "1.4.0"
xmlbeans = "5.3.0"

[libraries]
cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
commons-io = { module = "commons-io:commons-io", version.ref = "commonsIo" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "compiler" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
core-splashscreen-v110 = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreenVersion" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "compiler" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { module = "androidx.navigation:navigation-ui", version.ref = "navigationUi" }
poi = { module = "org.apache.poi:poi", version.ref = "poiOoxml" }
poi-ooxml = { module = "org.apache.poi:poi-ooxml", version.ref = "poiOoxml" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
xmlbeans = { module = "org.apache.xmlbeans:xmlbeans", version.ref = "xmlbeans" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
