[versions]
activityVersion = "1.8.2"
agp = "8.9.1"
androidxCoreSplashscreen = "1.0.1"
androidxJunit = "1.1.5"
appcompatVersion = "1.6.1"
cardview = "1.0.0"
commonsCompress = "1.28.0"
commonsIo = "2.21.0"
commonsIoVersion = "2.15.1"
compiler = "5.0.5"
compilerVersion = "4.16.0"
constraintlayoutVersion = "2.1.4"
core = "1.17.0"
coreSplashscreen = "1.2.0"
coreSplashscreenVersion = "1.1.0"
espressoCoreVersion = "3.5.1"
glide = "4.16.0"
gson = "2.13.2"
gsonVersion = "2.10.1"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.2"
constraintlayout = "2.2.1"
materialVersion = "1.11.0"
navigationFragment = "2.9.6"
navigationFragmentVersion = "2.7.7"
navigationUi = "2.7.6"
navigationUiVersion = "2.7.7"
poi = "5.2.5"
poiOoxml = "5.5.1"
poiOoxmlVersion = "5.2.5"
recyclerview = "1.4.0"
recyclerviewVersion = "1.3.2"
xmlbeans = "5.3.0"
xmlbeansVersion = "5.1.1"

[libraries]
activity-v182 = { module = "androidx.activity:activity", version.ref = "activityVersion" }
appcompat-v161 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commonsCompress" }
commons-io = { module = "commons-io:commons-io", version.ref = "commonsIo" }
commons-io-v2151 = { module = "commons-io:commons-io", version.ref = "commonsIoVersion" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "compiler" }
compiler-v4160 = { module = "com.github.bumptech.glide:compiler", version.ref = "compilerVersion" }
constraintlayout-v214 = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayoutVersion" }
core = { module = "androidx.core:core", version.ref = "core" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
core-splashscreen-v101 = { module = "androidx.core:core-splashscreen", version.ref = "androidxCoreSplashscreen" }
core-splashscreen-v110 = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreenVersion" }
espresso-core-v351 = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "compiler" }
glide-v4160 = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
gson-v2101 = { module = "com.google.code.gson:gson", version.ref = "gsonVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
junit-v115 = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material-v1110 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "navigationFragment" }
navigation-fragment-v277 = { module = "androidx.navigation:navigation-fragment", version.ref = "navigationFragmentVersion" }
navigation-ui = { module = "androidx.navigation:navigation-ui", version.ref = "navigationUi" }
navigation-ui-v277 = { module = "androidx.navigation:navigation-ui", version.ref = "navigationUiVersion" }
poi = { module = "org.apache.poi:poi", version.ref = "poiOoxml" }
poi-ooxml = { module = "org.apache.poi:poi-ooxml", version.ref = "poiOoxml" }
poi-ooxml-v525 = { module = "org.apache.poi:poi-ooxml", version.ref = "poiOoxmlVersion" }
poi-v525 = { module = "org.apache.poi:poi", version.ref = "poi" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
recyclerview-v132 = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerviewVersion" }
xmlbeans = { module = "org.apache.xmlbeans:xmlbeans", version.ref = "xmlbeans" }
xmlbeans-v511 = { module = "org.apache.xmlbeans:xmlbeans", version.ref = "xmlbeansVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
